USE Artwork;

CREATE TABLE Artist(
    A_ID INT PRIMARY KEY AUTO_INCREMENT,
    A_Name VARCHAR(22) NOT NULL,
    Bio VARCHAR(111) NOT NULL
);

CREATE TABLE Client(
    C_ID INT PRIMARY KEY AUTO_INCREMENT,
    C_Name VARCHAR(22) NOT NULL,
    Acc_Type VARCHAR(22) NOT NULL
);

CREATE TABLE Artworks(
    Artwork_ID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(44) NOT NULL,
    Price DECIMAL(7,2) NOT NULL,
    Statu VARCHAR(22) NOT NULL DEFAULT 'Available',
    Artist_FK INT,
    Client_FK INT,
    FOREIGN KEY (Artist_FK) REFERENCES Artist(A_ID) 
    ON DELETE CASCADE,
    FOREIGN KEY (Client_FK) REFERENCES Client(C_ID)
);
